name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: iterative/setup-dvc@v1
      -
        name: Pull data from DVC
        run: |
          dvc remote modify vkcloud endpointurl ${{ secrets.VKCLOUD_ENDPOINT_URL }} && \
          dvc remote modify vkcloud access_key_id ${{ secrets.VKCLOUD_ACCESS_KEY_ID }} && \
          dvc remote modify vkcloud secret_access_key ${{ secrets.VKCLOUD_SECRET_ACCESS_KEY }} && \
          dvc pull
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: olegggatttor/ml-pipe-bike-sharing-with-db-ansible-kafka:latest
          build-args: |
            ROOT_LOGIN_ANSIBLE=${{ secrets.ROOT_LOGIN_ANSIBLE }}
            ROOT_PASSWORD_ANSIBLE=${{ secrets.ROOT_PASSWORD_ANSIBLE }}
            KAFKA_HOST=${{ secrets.KAFKA_HOST }}
            KAFKA_PORT=${{ secrets.KAFKA_PORT }}
            ANSIBLE_PASSWORD=${{ secrets.ANSIBLE_PASSWORD }}
